# Generated by Django 2.0.5 on 2018-08-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_requested', models.DateTimeField(auto_now_add=True, verbose_name='Time Requested')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('discord_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Discord Username')),
                ('school_email', models.EmailField(max_length=254, verbose_name='School Email')),
                ('state', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Token')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Access Token')),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Refresh Token')),
                ('token_type', models.CharField(max_length=20, verbose_name='Token type')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires at')),
                ('join_success', models.BooleanField(default=False, verbose_name='Successfully joined the server')),
            ],
        ),
    ]
